data:extend{
    {
        type="int-setting",
        name="list-table-colspan",
        setting_type="runtime-global",
        default_value=2,
        minimum_value=1,
        maximum_value=5
    },
    {
        type="int-setting",
        name="entity-limit",
        setting_type="runtime-global",
        default_value=0,
        minimum_value=0,
        maximum_value=100
    },
    {
        type="int-setting",
        name="list-camera-min-width",
        setting_type="runtime-global",
        default_value=150,
        minimum_value=1
    },
    {
        type="int-setting",
        name="list-camera-min-height",
        setting_type="runtime-global",
        default_value=150,
        minimum_value=1
    },
    {
        type="double-setting",
        name="list-camera-zoom",
        setting_type="runtime-global",
        default_value=0.75,
        minimum_value=0.01
    },
    {
        type="int-setting",
        name="main-camera-min-width",
        setting_type="runtime-global",
        default_value=750,
        minimum_value=1
    },
    {
        type="int-setting",
        name="main-camera-min-height",
        setting_type="runtime-global",
        default_value=500,
        minimum_value=1
    },
    {
        type="double-setting",
        name="main-camera-zoom",
        setting_type="runtime-global",
        default_value=0.5,
        minimum_value=0.01
    },
    {
        type="double-setting",
        name="main-camera-zoom-diff",
        setting_type="runtime-global",
        default_value=1.1,
        minimum_value=0.01
    },
    {
        type="double-setting",
        name="scroll-pane-max-height",
        setting_type="runtime-global",
        default_value=750,
        minimum_value=1
    }
}
